version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region eu-west-1 | docker login --username AWS --password-stdin 152247411618.dkr.ecr.eu-west-1.amazonaws.com
      - REPOSITORY_URI=152247411618.dkr.ecr.eu-west-1.amazonaws.com/test-ecr

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"test-container","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinitions.json
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:latest > imageDetail.json

artifacts:
  files:
    - appspec.yaml
    - taskdef.json
    - image*.json

  secondary-artifacts:
    BuildArtifact:
      files:
        - appspec.yaml
        - taskdef.json
    ImageArtifact:
      files:
        - imageDetail.json
